### ISSUE TITLE
Party (0..2) objects not captured

### ISSUE THREAD

**Issue by Oblongs** [finos/cdm-object-builder#77]
### Steps to Reproduce:
1. Create an Eligibile Collateral Specification
2. Add an Identifier
3. Add the first Party, with a name
4. Add the second Party, with a name

### Expected Result:
In either table or JSON view, would expect to see both parties

### Actual Result:
Only the last Party is shown

### Environment:
(https://cdm-object-builder.finos.org/)
CDM-JAVA5.0.1

### Additional Context:
{
  "identifier": [
    {
      "assignedIdentifier": [
        {
          "identifier": {
            "value": "A12345678"
          }
        }
      ]
    },
    {
      "assignedIdentifier": [
        {
          "identifier": {
            "value": "sdsadasd"
          }
        }
      ]
    }
  ],
  "party": {
    "name": {
      "value": "BNPP"
    }
  }
}

![Screenshot 2023-12-05 173500](https://github.com/finos/cdm-object-builder/assets/146734978/f5aaac2f-3c6f-4e4a-b371-2a93b89ad349)

**Comment by minesh-s-patel** [comment]
Fixed in PR https://github.com/finos/cdm-object-builder/issues/77
